name: Build Java (mycode)

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - name: Compile mycode
        run: |
          mkdir -p out
          if ls mycode/*.java 1> /dev/null 2>&1; then
            javac -d out mycode/*.java
            echo "Compiled mycode successfully."
          else
            echo "No Java files in mycode to compile."
          fi
